### ISSUE TITLE
How do you install this? 

### ISSUE THREAD

**Issue by nklush** [karaggeorge/kap-playback-speed#2]
Thanks for making this! How do I install it? It's disabled in option in Preferences. I tried downloading it and moving it into Kap's "plugin" folder, but that's not doing anything. 👀 

<img width="481" alt="Screen Shot 2020-03-29 at 6 34 57 PM" src="https://user-images.githubusercontent.com/6153192/77862835-0fd41800-71ec-11ea-9525-2f5dda2bab10.png">

**Comment by karaggeorge** [comment]
Hey @nklush this (and all other disabled plugins) are only compatible with Kap 3.2.0, which should be released very soon, hopefully this week. If you want to test it in the meantime, you'll have to use a test build as described here: https://github.com/wulkano/kap/issues/811#issuecomment-600258113

With the upcoming version, we also have a better message for when plugins don't meet the minimum Kap version

**Comment by crstauf** [comment]
TIL: Kap doesn't auto-update.

**Comment by karaggeorge** [comment]
Hey @crstauf 

Kap does indeed auto-update. What version were you running on that you weren't able to to auto-update

**Comment by crstauf** [comment]
@karaggeorge Mmm i don’t recall for sure... 3.0.x...?

It was the version right after Apple developer signature was added.
